//==========================================================================
// File Name   : A1601.inc
// Description : SACM A1601 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __A1601_INC__
.define __A1601_INC__

.external F_SACM_A1601_Initial
.external F_SACM_A1601_Play
.external F_SACM_A1601_Stop
.external F_SACM_A1601_Volume
.external F_SACM_A1601_Pause
.external F_SACM_A1601_Resume
.external F_SACM_A1601_Status
.external F_SACM_A1601_ServiceLoop
.external F_ISR_Service_SACM_A1601

.endif
//========================================================================================        
// End of SACM_A1601.inc
//========================================================================================