//==========================================================================
// File Name   : A1601_CH2.inc
// Description : SACM A1601_CH2 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __A1601_CH2_INC__
.define __A1601_CH2_INC__

.external F_SACM_A1601_CH2_Initial
.external F_SACM_A1601_CH2_Play
.external F_SACM_A1601_CH2_Stop
.external F_SACM_A1601_CH2_Volume
.external F_SACM_A1601_CH2_Pause
.external F_SACM_A1601_CH2_Resume
.external F_SACM_A1601_CH2_Status
.external F_SACM_A1601_CH2_ServiceLoop
.external F_ISR_Service_SACM_A1601_CH2

.endif
//========================================================================================        
// End of SACM_A1601_CH2.inc
//========================================================================================