//==========================================================================
// File Name   : A1600.inc
// Description : SACM A1600 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __A1600_INC__
.define __A1600_INC__

.external F_SACM_A1600_Initial
.external F_SACM_A1600_Play
.external F_SACM_A1600_Stop
.external F_SACM_A1600_Volume
.external F_SACM_A1600_Pause
.external F_SACM_A1600_Resume
.external F_SACM_A1600_Status
.external F_SACM_A1600_ServiceLoop
.external F_ISR_Service_SACM_A1600

.endif
//========================================================================================        
// End of SACM_A1600.inc
//========================================================================================