//==========================================================================
// File Name   : A1800.inc
// Description : SACM A1800 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __A1800_INC__
.define __A1800_INC__

.external F_SACM_A1800_Initial
.external F_SACM_A1800_Play
.external F_SACM_A1800_Stop
.external F_SACM_A1800_Volume
.external F_SACM_A1800_Pause
.external F_SACM_A1800_Resume
.external F_SACM_A1800_Status
.external F_SACM_A1800_ServiceLoop
.external F_ISR_Service_SACM_A1800

.endif
//========================================================================================        
// End of SACM_A1800.inc
//========================================================================================