//==========================================================================
// File Name   : A3600.inc
// Description : SACM A3600 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __A3600_INC__
.define __A3600_INC__

.external F_SACM_A3600_Initial
.external F_SACM_A3600_Play
.external F_SACM_A3600_Stop
.external F_SACM_A3600_Volume
.external F_SACM_A3600_Pause
.external F_SACM_A3600_Resume
.external F_SACM_A3600_Status
.external F_SACM_A3600_ServiceLoop
.external F_ISR_Service_SACM_A3600

.endif
//========================================================================================        
// End of SACM_A3600.inc
//========================================================================================