//==========================================================================
// File Name   : DVR1800.inc
// Description : SACM DVR1800 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __DVR1800_INC__
.define __DVR1800_INC__

.external F_SACM_DVR1800_Initial
.external F_SACM_DVR1800_Rec
.external F_SACM_DVR1800_Play
.external F_SACM_DVR1800_Stop
.external F_SACM_DVR1800_Volume
.external F_SACM_DVR1800_Pause
.external F_SACM_DVR1800_Resume
.external F_SACM_DVR1800_Status
.external F_SACM_DVR1800_ServiceLoop
.external F_ISR_Service_SACM_DVR1800

.endif
//========================================================================================        
// End of SACM_DVR1800.inc
//========================================================================================