//==========================================================================
// File Name   : DVR1600.inc
// Description : SACM DVR1600 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __DVR1600_INC__
.define __DVR1600_INC__

.external F_SACM_DVR1600_Initial
.external F_SACM_DVR1600_Rec
.external F_SACM_DVR1600_Play
.external F_SACM_DVR1600_Stop
.external F_SACM_DVR1600_Volume
.external F_SACM_DVR1600_Pause
.external F_SACM_DVR1600_Resume
.external F_SACM_DVR1600_Status
.external F_SACM_DVR1600_ServiceLoop
.external F_ISR_Service_SACM_DVR1600

.endif
//========================================================================================        
// End of SACM_DVR1600.inc
//========================================================================================