//==========================================================================
// File Name   : DVR3200.inc
// Description : SACM DVR3200 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __DVR3200_INC__
.define __DVR3200_INC__

.external F_SACM_DVR3200_Initial
.external F_SACM_DVR3200_Rec
.external F_SACM_DVR3200_Play
.external F_SACM_DVR3200_Stop
.external F_SACM_DVR3200_Volume
.external F_SACM_DVR3200_Pause
.external F_SACM_DVR3200_Resume
.external F_SACM_DVR3200_Status
.external F_SACM_DVR3200_ServiceLoop
.external F_ISR_Service_SACM_DVR3200

.endif
//========================================================================================        
// End of SACM_DVR3200.inc
//========================================================================================