//==========================================================================
// File Name   : DVR4800.inc
// Description : SACM DVR4800 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __DVR4800_INC__
.define __DVR4800_INC__

.external F_SACM_DVR4800_Initial
.external F_SACM_DVR4800_Rec
.external F_SACM_DVR4800_Play
.external F_SACM_DVR4800_Stop
.external F_SACM_DVR4800_Volume
.external F_SACM_DVR4800_Pause
.external F_SACM_DVR4800_Resume
.external F_SACM_DVR4800_Status
.external F_SACM_DVR4800_ServiceLoop
.external F_ISR_Service_SACM_DVR4800

.endif
//========================================================================================        
// End of SACM_DVR4800.inc
//========================================================================================