//==========================================================================
// File Name   : DVR520.inc
// Description : SACM DVR520 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __DVR520_INC__
.define __DVR520_INC__

.external F_SACM_DVR520_Initial
.external F_SACM_DVR520_Rec
.external F_SACM_DVR520_Play
.external F_SACM_DVR520_Stop
.external F_SACM_DVR520_Volume
.external F_SACM_DVR520_Pause
.external F_SACM_DVR520_Resume
.external F_SACM_DVR520_Status
.external F_SACM_DVR520_ServiceLoop
.external F_ISR_Service_SACM_DVR520

.endif
//========================================================================================        
// End of SACM_DVR520.inc
//========================================================================================