//==========================================================================
// File Name   : MS02.inc
// Description : SACM MS02 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __MS02_INC__
.define __MS02_INC__

.external F_SACM_MS02_Initial
.external F_SACM_MS02_Play
.external F_SACM_MS02_Stop
.external F_SACM_MS02_Volume
.external F_SACM_MS02_Pause
.external F_SACM_MS02_Resume
.external F_SACM_MS02_Status
.external F_SACM_MS02_ServiceLoop
.external F_ISR_Service_SACM_MS02

.endif
//========================================================================================        
// End of SACM_MS02.inc
//========================================================================================