//==========================================================================
// File Name   : PCM.inc
// Description : SACM PCM API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __PCM_INC__
.define __PCM_INC__

.external F_SACM_PCM_Initial
.external F_SACM_PCM_Rec
.external F_SACM_PCM_Play
.external F_SACM_PCM_Stop
.external F_SACM_PCM_Volume
.external F_SACM_PCM_Pause
.external F_SACM_PCM_Resume
.external F_SACM_PCM_Status
.external F_SACM_PCM_ServiceLoop
.external F_ISR_Service_SACM_PCM

.endif
//========================================================================================        
// End of SACM_PCM.inc
//========================================================================================