//==========================================================================
// File Name   : S200.inc
// Description : SACM S200 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __S200_INC__
.define __S200_INC__

.external F_SACM_S200_Initial
.external F_SACM_S200_Play
.external F_SACM_S200_Stop
.external F_SACM_S200_Volume
.external F_SACM_S200_Pause
.external F_SACM_S200_Resume
.external F_SACM_S200_Status
.external F_SACM_S200_ServiceLoop
.external F_ISR_Service_SACM_S200

.endif
//========================================================================================        
// End of SACM_S200.inc
//========================================================================================