//==========================================================================
// File Name   : S480.inc
// Description : SACM S480 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __S480_INC__
.define __S480_INC__

.external F_SACM_S480_Initial
.external F_SACM_S480_Play
.external F_SACM_S480_Stop
.external F_SACM_S480_Volume
.external F_SACM_S480_Pause
.external F_SACM_S480_Resume
.external F_SACM_S480_Status
.external F_SACM_S480_ServiceLoop
.external F_ISR_Service_SACM_S480

.endif
//========================================================================================        
// End of SACM_S480.inc
//========================================================================================