//==========================================================================
// File Name   : S530.inc
// Description : SACM S530 API declaration
// Written by  : Ray Cheng
// Last modified date:
//              2005/12/26
//==========================================================================
.ifndef __S530_INC__
.define __S530_INC__

.external F_SACM_S530_Initial
.external F_SACM_S530_Play
.external F_SACM_S530_Stop
.external F_SACM_S530_Volume
.external F_SACM_S530_Pause
.external F_SACM_S530_Resume
.external F_SACM_S530_Status
.external F_SACM_S530_ServiceLoop
.external F_ISR_Service_SACM_S530

.endif
//========================================================================================        
// End of SACM_S530.inc
//========================================================================================